dbt_snowflake_demo:
  outputs:
    dev:
      account: name.location
      database: db_name
      password: xxx
      role: role_name
      schema: schema_name
      threads: 1
      type: snowflake
      user: user_name
      warehouse: wh_name
  target: dev
